// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RichLife.Infrastructure.Persistence;

#nullable disable

namespace RichLife.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20261009154221_BusinessTaxes")]
    partial class BusinessTaxes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RichLife.Domain.Catalogue.BusinessCatalogueEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("BaseEmployeeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseIncomePerSecond")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlySalaryCost")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("OpeningCost")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<int>("RequiredPrestige")
                        .HasColumnType("integer");

                    b.Property<int>("Sector")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("catalogue_businesses", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Catalogue.LuxuryCatalogueEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageCredit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageSourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<int>("RequiredPrestige")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("luxury_catalogue", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Catalogue.ManagerName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("manager_names", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PassiveIncomeBonus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AskingPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("CatalogueId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossIncomePerSecond")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("ManagerNameId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ManagerUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlySalaryCost")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("OpeningCost")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<int>("RequiredPrestige")
                        .HasColumnType("integer");

                    b.Property<int>("Sector")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxDue")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<DateTime>("TaxPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TaxableEarnings")
                        .HasPrecision(24, 6)
                        .HasColumnType("numeric(24,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("ManagerNameId");

                    b.HasIndex("CompanyId", "CatalogueId")
                        .IsUnique();

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.BusinessAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IncomePerSecond")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessAssets");
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllTimeEarnings")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("AvatarId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("BoostUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Cash")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<bool>("CashOverridePending")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Diamonds")
                        .HasColumnType("integer");

                    b.Property<string>("FeaturedBadgeId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("OfflineBonusAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<DateTime?>("OfflineBonusUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PassiveIncomePerSecond")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PrestigeCount")
                        .HasColumnType("integer");

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxesPaid")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AllTimeEarnings");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.DiamondTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.ToTable("diamond_transactions", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BankIcon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ForgivenAmount")
                        .HasPrecision(24, 4)
                        .HasColumnType("numeric(24,4)");

                    b.Property<decimal>("InstallmentAmount")
                        .HasPrecision(24, 4)
                        .HasColumnType("numeric(24,4)");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<int>("MissedPayments")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextPaymentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Paid")
                        .HasPrecision(24, 4)
                        .HasColumnType("numeric(24,4)");

                    b.Property<decimal>("Penalties")
                        .HasPrecision(24, 4)
                        .HasColumnType("numeric(24,4)");

                    b.Property<decimal>("Principal")
                        .HasPrecision(24, 4)
                        .HasColumnType("numeric(24,4)");

                    b.Property<DateTime?>("RepaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalRepay")
                        .HasPrecision(24, 4)
                        .HasColumnType("numeric(24,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("IX_loans_CompanyId_active")
                        .HasFilter("\"RepaidAt\" IS NULL");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.LuxuryAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogueId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageCredit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("IncomeMultiplierBonus")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("CompanyId", "CatalogueId")
                        .IsUnique();

                    b.ToTable("LuxuryAssets", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefreshToken");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("RichLife.Domain.Catalogue.BusinessCatalogueEntry", b =>
                {
                    b.OwnsMany("RichLife.Domain.Catalogue.AssetCatalogueEntry", "AvailableAssets", b1 =>
                        {
                            b1.Property<string>("BusinessCatalogueId")
                                .HasColumnType("character varying(60)");

                            b1.Property<string>("Id")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("FixedIncomePerSecond")
                                .HasPrecision(20, 6)
                                .HasColumnType("numeric(20,6)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<decimal>("Price")
                                .HasPrecision(20, 4)
                                .HasColumnType("numeric(20,4)");

                            b1.Property<int>("UnlockAtAssetCount")
                                .HasColumnType("integer");

                            b1.HasKey("BusinessCatalogueId", "Id");

                            b1.ToTable("catalogue_assets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BusinessCatalogueId");
                        });

                    b.Navigation("AvailableAssets");
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Asset", b =>
                {
                    b.HasOne("RichLife.Domain.Entities.Company", null)
                        .WithMany("Assets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Business", b =>
                {
                    b.HasOne("RichLife.Domain.Catalogue.BusinessCatalogueEntry", null)
                        .WithMany()
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RichLife.Domain.Entities.Company", null)
                        .WithMany("Businesses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RichLife.Domain.Catalogue.ManagerName", null)
                        .WithMany()
                        .HasForeignKey("ManagerNameId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RichLife.Domain.Entities.BusinessAsset", b =>
                {
                    b.HasOne("RichLife.Domain.Entities.Business", null)
                        .WithMany("Assets")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Company", b =>
                {
                    b.HasOne("RichLife.Domain.Entities.Player", null)
                        .WithOne("Company")
                        .HasForeignKey("RichLife.Domain.Entities.Company", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RichLife.Domain.Entities.CompanyAchievement", "Achievements", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<DateTime>("UnlockedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CompanyId", "Code");

                            b1.ToTable("company_achievements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("RichLife.Domain.Entities.CompanyAvatar", "Avatars", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarId")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<DateTime>("PurchasedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CompanyId", "AvatarId");

                            b1.ToTable("company_avatars", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("RichLife.Domain.Entities.CompanyBadge", "Badges", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BadgeId")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<DateTime>("PurchasedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CompanyId", "BadgeId");

                            b1.ToTable("company_badges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Achievements");

                    b.Navigation("Avatars");

                    b.Navigation("Badges");
                });

            modelBuilder.Entity("RichLife.Domain.Entities.DiamondTransaction", b =>
                {
                    b.HasOne("RichLife.Domain.Entities.Company", null)
                        .WithMany("DiamondLedger")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Loan", b =>
                {
                    b.HasOne("RichLife.Domain.Entities.Company", null)
                        .WithMany("Loans")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RichLife.Domain.Entities.LuxuryAsset", b =>
                {
                    b.HasOne("RichLife.Domain.Catalogue.LuxuryCatalogueEntry", null)
                        .WithMany()
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RichLife.Domain.Entities.Company", null)
                        .WithMany("LuxuryAssets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Business", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Company", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Businesses");

                    b.Navigation("DiamondLedger");

                    b.Navigation("Loans");

                    b.Navigation("LuxuryAssets");
                });

            modelBuilder.Entity("RichLife.Domain.Entities.Player", b =>
                {
                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
